"""initial schema

Revision ID: 4a11d8bdf881
Revises: 
Create Date: 2026-03-07 23:41:44.685646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '4a11d8bdf881'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('corriente', sa.String(), nullable=False),
    sa.Column('ideas_clave', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('corriente', sa.String(), nullable=False),
    sa.Column('dilema', sa.Text(), nullable=False),
    sa.Column('pregunta_abierta', sa.Text(), nullable=False),
    sa.Column('temas', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sesgos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('libro_rec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('apertura_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('reaccion_cita', sa.Text(), nullable=True),
    sa.Column('dilema_eleccion', sa.Boolean(), nullable=True),
    sa.Column('dilema_razon', sa.Text(), nullable=True),
    sa.Column('pregunta_resp', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('sesgos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('influencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('informe', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('responses')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('prompts')
    op.drop_table('authors')
    # ### end Alembic commands ###
